version: '3.8'

services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=your-secret-key
    depends_on:
      - postgres
    volumes:
      - ./auth-service/src:/usr/src/app/src
      - ./auth-service/package.json:/usr/src/app/package.json
      - ./auth-service/tsconfig.json:/usr/src/app/tsconfig.json
    networks:
      - backend-network

  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URI=mongodb://mongodb:27017/event_db
    depends_on:
      - mongodb
    volumes:
      - ./event-service/src:/usr/src/app/src
      - ./event-service/package.json:/usr/src/app/package.json
      - ./event-service/tsconfig.json:/usr/src/app/tsconfig.json
    networks:
      - backend-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./auth-service/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data: